# 🍎 파이썬 머신러닝 완벽 가이드 혼공

### 2019.03.05 ~ 2019.03.28 교재 1,2장

코로나19 사태로 1,2장은 혼자 공부해야 하는데, 양이 많아서 농땡이 부리지 말고 열심히 하자^*^

01. 파이썬 기반의 머신러닝과 생태계 이해 
02. 사이킷런으로 시작하는 머신러닝

Let's get started⚽️!


### 2020-03-05-Thu

진도: 1장 01. 머신러닝의 개념 / 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지 / 03. 넘파이 ~ (1쪽 ~ 16쪽) 


In [4]:
# 정상적으로 아나콘다 잘 깔려있음.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn 
from sklearn.model_selection import train_test_split


### 넘파이 ndarray 개요 

- **array1.array()** : 괄호 안에 들어있는 것을 numpy의 ndarray 형태로 변환해주는 것. 
- **array1. shape** : array1의 형태에 대해 알려줌. ex. (2,3) 함수가 아니므로 ()를 붙이지 말 것. 
- 이런 형태에 대해 알아야 하는 이유는 **데이터값은 동일하나 차원이 달라서 오류가 발생하는 경우가 빈번**하기 때문임. 따라서 후에 배울 reshape() 함수를 사용해 조정해주는 것이 중요.


In [11]:
import numpy as np

array1 = np.array([1,2,3])
array1.shape   # 1차원 데이터

(3,)

In [14]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
type(array2)

# type은 list냐 ndarray냐처럼 데이터 형태를 말해주는 것.

numpy.ndarray

In [13]:
array2.shape  # 2차원 데이터

(2, 3)

In [17]:
array3 = np.array([[1,2,3]])
array3.shape

(1, 3)

- array.ndim : 몇차원인지를 알려주는 것.

In [22]:
'array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim)

'array1: 1차원, array2: 2차원, array3:  2차원'

### 2020-03-06-Fri

진도: 03. 넘파이 ~ (16쪽 ~ 23쪽) 

#### ndarray의 데이터 타입

- **array1.dtype**: ndarray의 데이터 타입이 뭔지 알 수 있음. type()과 다른 것에 주의!

In [1]:
list1 = [1,2,3]
type(list1)

list

In [4]:
import numpy as np

array1 = np.array(list1)
array1.dtype

dtype('int64')

In [7]:
type(array1)  #type()은 데이터 형태 자체를 알려줌. 

numpy.ndarray

- 다양한 데이터 타입(int, float, string..)이 함께 있을 때에 ndarray로 바꿀 때에는, **데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용**함.


In [8]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)  #모두 문자열로 변화.

['1' '2' 'test'] <U21


In [9]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  #모두 실수형으로 변화.

[1. 2. 3.] float64


- **array_int.astype('float64'**: **astype()을 사용해서 데이터 타입을 변화시킬 수 있음.** 보통 이 때에는 원하는 타입을 문자열로 지정하면 됨. **메모리를 더 절약해야 할 때 이용**하는데, 파이썬 기반 머신러닝 알고리즘은 대부분 메모리로 데이터를 전체 로딩하기 때문에 대용량 데이터 로딩 시 수행속도가 느려지거나 메모리 부족으로 오류 발생할 수 있음.

In [10]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')  #float64로 바꿔라.
print(array_float, array_float.dtype) 

[1. 2. 3.] float64


In [11]:
array_int1 = array_float.astype('int32')  #int32로 바꿔라.
print(array_int1, array_int1.dtype)

[1 2 3] int32


#### ndarray를 편리하게 생성하기 - arange, zeros, ones

- 주용도: 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우!
- np.arange(): 파이썬 range()처럼 0부터 n만큼 숫자를 만들어냄.

In [12]:
sequence_array = np.arange(10)
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
sequence_array2 = np.arange(1,10) #제일 처음부터 마지막 수 전까지!
sequence_array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- np.zeros(): 전체 데이터가 모두 0으로 구성. 괄호 안 데이터 shape은 튜플 형태로 들어가야 함.
- np.ones(): 전체 데이터가 모두 1로 구성. 

In [14]:
zero_array = np.zeros((3,2), dtype ='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [15]:
one_array = np.ones((3,2)) #default는 float64
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### ndarray의 차원과 크기를 변경하는 reshape()

- array1.reshape(): ndarray를 특정 차원 및 크기로 변환

In [16]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [17]:
array2 = array1.reshape(2,5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
array3 = array1.reshape(5,2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape()를 실전에서 효율적으로 사용하는 경우 
: **인자로 -1을 적용할 때**임. 이렇게 사용하면, 특정 열/행만 지정하고 나머지는 호환가능하도록 설정할 수 있음. (그럼에도 불구하고 호환불가능한 것이 존재하기는 함.) 

In [20]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
array2 = array1.reshape(-1,5) #컬럼은 반드시 5개로! 로우는 임의로!
print(array2, array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [25]:
array3 = array1.reshape(5,-1)  #로우는 반드시 5개로! 컬럼은 임의로!
print(array3, array3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


- **reshape(-1,1)**과 같은 형태로 자주 사용됨. ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장함.

In [29]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) #tolist()는 리스트 자료형으로 변환한 것.(프린트 출력시 이해가 더 쉬워서)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [30]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [31]:
# 1차원 ndarray를 2차원 ndarray로 변환 
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 2020-03-08-Sun

진도: 03. 넘파이 ~ (23쪽 ~ 쪽) 

#### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

1. 단일 값 추출(특정한 데이터만 추출) 
2. 슬라이싱(Slicing)
3. 팬시 인덱싱(Fancy Indexing)
4. 불린 인덱싱(Boolean Indexing)

##### 단일 값 추출 
- 판다스의 인덱싱과 유사
- array1d[n]: n번째 값 추출 
- array2d[3,4]: 3번째 row, 4번째 column 값 추출
- **axis = 0**은 **row**이고, **axis = 1**은 **column**이라는게 중요!

In [7]:
# 1차원 ndarray에서 단일 값 추출하기
array1 = np.arange(start=1, stop=10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
value = array1[2]
print(value, type(value))  #단일 데이터값 추출시 타입은 ndarray가 아님.

3 <class 'numpy.int64'>


In [9]:
# ndarray의 데이터값도 수정 가능 
array1[0] = 9
array1[8] = 0
array1

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [10]:
# 다차원 ndarray에서 단일 값 추출하기
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print('(row=2, col=2) index 가리키는 값: ', array2d[2,2])

(row=2, col=2) index 가리키는 값:  9


##### 슬라이싱

- 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 **ndarray 타입**임.


In [15]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3, type(array3))

[1 2 3] <class 'numpy.ndarray'>


In [21]:
array4 = array1[:3]
array5 = array1[3:]
array6 = array1[:]
print(array4, array5, array6)

[1 2 3] [4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]


In [22]:
# 다차원 ndarray 슬라이싱 
array2d = array1d.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array2d[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [24]:
array2d[1:3, 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

##### 팬시 인덱싱 
- 약간 3(1+2) = 3*1 + 3*2와 같은 것. 

In [28]:
array3 = array2d[[0,1],2]
print(array2d, array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [3 6]


In [30]:
array4 = array2d[[0,1], 0:2]  #(0,0),(0,1),(1,0),(1,1)을 반환
array4

array([[1, 2],
       [4, 5]])

In [31]:
array5 = array2d[[0,1]]  #뒤에가 생략되면 전체!
array5

array([[1, 2, 3],
       [4, 5, 6]])

##### 불린 인덱싱
- 조건 필터링과 검색을 동시에 할 수 있음. 
- [] 안에 array1d > 5 Boolean indexing을 적용하면 됨.

In [32]:
array1d = np.arange(1,10)
array3 = array1d[array1d > 5]  # array3 중에 5보다 큰 값만 가져와라.
array3

array([6, 7, 8, 9])

In [33]:
array1d > 5  # 조건식을 붙이면, False, True로 이뤄진 ndarray를 반환함.

array([False, False, False, False, False,  True,  True,  True,  True])

#### 행렬의 정렬 - sort()와 argsort()

##### 행렬 정렬
- **np.sort()**: 넘파이에서 sort()를 호출하는 방식 
- **ndarray.sort()**: 행렬 자체에서 sort()를 호출하는 방식 
- 전자의 경우 원본 행렬을 유지한 채 정렬된 행렬을 반환하지만, 후자의 경우 원본 행렬 자체를 정렬한 상태로 변환하고 반환 값은 None임. 
- 내림차순 정렬: np.sort(value)**[::-1]**

In [38]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬 
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]


In [39]:
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [40]:
# np.sort(), ndarray.sort() 기본적으로 오름차순으로 정렬 
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- axis=0으로 로우 방향 정렬, axis=1로 컬럼 방향 정렬

In [42]:
array2d = np.array([[8,12],[7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
sort_array2d_axis0

array([[ 7,  1],
       [ 8, 12]])

In [43]:
sort_array2d_axis1 = np.sort(array2d, axis=1)
sort_array2d_axis1

array([[ 8, 12],
       [ 1,  7]])

##### 🍑🍑🍑정렬된 행렬의 (원본) 인덱스 반환하기

- **np.argsort()**: 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환
- 넘파이에서 매우 활용도 높음. ex) 성적 순으로 학생 이름 정렬

In [44]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
sort_indices

array([1, 0, 3, 2])

In [45]:
# 내림차순 일 때 원본 인덱스 값 
sort_indices_desc = np.argsort(org_array)[::-1]
sort_indices_desc

array([2, 3, 0, 1])

In [47]:
name_array = np.array(['John', 'Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 socre_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 socre_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


 #### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기 
 
 ##### 행렬 내적 (행렬 곱) 
 
 - **np.dot()**: 행렬 곱 


In [49]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
print('행렬 내적 결과:\n', np.dot(A,B))

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


##### 전치 행렬 
- **np.transpose()**: 전치 행렬 

In [51]:
A = np.array([[1,2],
             [3,4],
             [5,6]])
print('A의 전치 행렬:\n', np.transpose(A))

A의 전치 행렬:
 [[1 3 5]
 [2 4 6]]
